# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5718d863c8a8a44e837f007c163feb342ee67ae47a14873d3bc890a0d83fb4aae4132f72ec0491f2f4807e7be28861eb1054e53cfae89a614885bb25a4c14df

test:
  secret_key_base: 14e99bd49ca9e89163fa293d88b9642b8962926188c9872509d41a845cbbc6905274538a9082f0f38870802fbf4b9ef8309b75ded1d419f46a8ed9fd5c18a634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
